### PR TITLE
Game action and menu button#80

### LINKED ISSUE #80: GAME-COMPONENT: Actions
The component for the four actions in the bottom left.
REMEMBER:
- Create functions necessary for the issue
- Design the component according to the design (see image)
- Before you code, see if there is any comments/Todo's in your files and do them as well. 

07a - PlayPhaseView
(All images can be found in our Google drive - development - game views)

### LINKED ISSUE #82: GAME-COMPONENT: Menu bottom
This one shouldn't maybe be on in it's own since it is too small, but well well. Basically just create the bottom, make a hover on it but it dosen't lead to anything (yet). 
REMEMBER:
- Design the component according to the design (see image)

07a - PlayPhaseView
(All images can be found in our Google drive - development - game views)

### PR DESCRIPTION
**Pull request by petterekedahl**
Completed the action component - they lack the correct font, since I wasn't able to get a hold of the fonts through the variables.
I will replace current CSS with the correct variable through a later issue.
The menu button is also added, for now with position absolute, I will take to Sebbe about how I could fix that though, since I wasn't able to do it the way I wanted.

The black background on the action-element is not there in the code anymore, I put it there for the screenshots so that you could see the components, the same applies to the menu-button border.

The different colors of the action-component is - white while nothing, darker bg-color while pressed, light bg-color while cooldown is running.

Closes #80 
Skärmavbild 2021-04-29 kl  20 22 08

Closes #82 
Skärmavbild 2021-04-29 kl  20 02 44
Skärmavbild 2021-04-29 kl  20 03 37
Skärmavbild 2021-04-29 kl  20 05 20

### CODE REVIEW

**Comment by trumtomte** [comment]
What does it look like when you select 4 spells? is the height of the spells just 1/2?

**Comment by petterekedahl** [comment]
Yes, the container is a grid with 2 columns, so in the case of a player having 4 spells they would be placed underneath and the buttons would take 50% - gap of the container

**Comment by trumtomte** [comment]
Great!

**Comment by petterekedahl** [comment]
Since there are no variables in the variables.css that include a black font-color, or the on-cooldown- and selected-button colors I'll add these to the variable sheet as well incase it's needed. For some reason my fetch won't include the variables.css though, so I'll have to do that in a new branch, preferably when I work on an other issue.

**Review by VilmaNilsson — APPROVED** [review]
Looks great! 
And yes, add the variables when you can in that css-file.

**Pull request merged**
